In [1]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('GPD_Provinsi_Indo.csv')
df

                     Provinsi  2016  2017   2018   2019  2020
0                        Aceh  3.29  4.18   4.61   4.14 -0.37
1                        Bali  6.33  5.56   6.31   5.60 -9.31
2                      Banten  5.28  5.75   5.77   5.29 -3.38
3                    Bengkulu  5.28  4.98   4.97   4.94  0.02
4               DI Yogyakarta  5.05  5.26   6.20   6.59 -2.69
5                 DKI Jakarta  5.87  6.20   6.11   5.82 -2.36
6                   Gorontalo  6.52  6.73   6.49   6.40 -0.02
7                   Indonesia  5.03  5.07   5.17   5.02 -2.07
8                       Jambi  4.37  4.60   4.69   4.37 -0.46
9                  Jawa Barat  5.66  5.33   5.65   5.07 -2.44
10                Jawa Tengah  5.25  5.26   5.30   5.40 -2.65
11                 Jawa Timur  5.57  5.46   5.47   5.52 -2.39
12           Kalimantan Barat  5.20  5.17   5.07   5.09 -1.82
13         Kalimantan Selatan  4.40  5.28   5.08   4.08 -1.81
14          Kalimantan Tengah  6.35  6.73   5.61   6.12 -1.40
15           Kalimantan Timur -0.38  3.13   2.64   4.74 -2.85
16           Kalimantan Utara  3.55  6.80   5.36   6.90 -1.11
17  Kepulauan Bangka Belitung  4.10  4.47   4.45   3.32 -2.30
18             Kepulauan Riau  4.98  1.98   4.47   4.84 -3.80
19                    Lampung  5.14  5.16   5.23   5.26 -1.67
20                     Maluku  5.73  5.82   5.91   5.41 -0.92
21               Maluku Utara  5.77  7.67   7.86   6.10  4.92
22        Nusa Tenggara Barat  5.81  0.09   4.50   3.90 -0.64
23        Nusa Tenggara Timur  5.12  5.11   5.11   5.24 -0.83
24                      Papua  9.14  4.64   7.32  15.75  2.32
25                Papua Barat  4.52  4.02   6.25   2.66 -0.77
26                       Riau  2.18  2.66   2.35   2.81 -1.12
27             Sulawesi Barat  6.01  6.39   6.26   5.67 -2.42
28           Sulawesi Selatan  7.42  7.21   7.04   6.91 -0.70
29            Sulawesi Tengah  9.94  7.10  20.60   8.83  4.86
30          Sulawesi Tenggara  6.51  6.76   6.40   6.50 -0.65
31             Sulawesi Utara  6.16  6.31   6.00   5.65 -0.99
32             Sumatera Barat  5.27  5.30   5.14   5.01 -1.60
33           Sumatera Selatan  5.04  5.51   6.01   5.69 -0.11
34             Sumatera Utara  5.18  5.12   5.18   5.22 -1.07

In [3]:
df.to_xarray

<bound method NDFrame.to_xarray of                      Provinsi  2016  2017   2018   2019  2020
0                        Aceh  3.29  4.18   4.61   4.14 -0.37
1                        Bali  6.33  5.56   6.31   5.60 -9.31
2                      Banten  5.28  5.75   5.77   5.29 -3.38
3                    Bengkulu  5.28  4.98   4.97   4.94  0.02
4               DI Yogyakarta  5.05  5.26   6.20   6.59 -2.69
5                 DKI Jakarta  5.87  6.20   6.11   5.82 -2.36
6                   Gorontalo  6.52  6.73   6.49   6.40 -0.02
7                   Indonesia  5.03  5.07   5.17   5.02 -2.07
8                       Jambi  4.37  4.60   4.69   4.37 -0.46
9                  Jawa Barat  5.66  5.33   5.65   5.07 -2.44
10                Jawa Tengah  5.25  5.26   5.30   5.40 -2.65
11                 Jawa Timur  5.57  5.46   5.47   5.52 -2.39
12           Kalimantan Barat  5.20  5.17   5.07   5.09 -1.82
13         Kalimantan Selatan  4.40  5.28   5.08   4.08 -1.81
14          Kalimantan Tengah  6.35  6.73   5.61   6.12 -1.40
15           Kalimantan Timur -0.38  3.13   2.64   4.74 -2.85
16           Kalimantan Utara  3.55  6.80   5.36   6.90 -1.11
17  Kepulauan Bangka Belitung  4.10  4.47   4.45   3.32 -2.30
18             Kepulauan Riau  4.98  1.98   4.47   4.84 -3.80
19                    Lampung  5.14  5.16   5.23   5.26 -1.67
20                     Maluku  5.73  5.82   5.91   5.41 -0.92
21               Maluku Utara  5.77  7.67   7.86   6.10  4.92
22        Nusa Tenggara Barat  5.81  0.09   4.50   3.90 -0.64
23        Nusa Tenggara Timur  5.12  5.11   5.11   5.24 -0.83
24                      Papua  9.14  4.64   7.32  15.75  2.32
25                Papua Barat  4.52  4.02   6.25   2.66 -0.77
26                       Riau  2.18  2.66   2.35   2.81 -1.12
27             Sulawesi Barat  6.01  6.39   6.26   5.67 -2.42
28           Sulawesi Selatan  7.42  7.21   7.04   6.91 -0.70
29            Sulawesi Tengah  9.94  7.10  20.60   8.83  4.86
30          Sulawesi Tenggara  6.51  6.76   6.40   6.50 -0.65
31             Sulawesi Utara  6.16  6.31   6.00   5.65 -0.99
32             Sumatera Barat  5.27  5.30   5.14   5.01 -1.60
33           Sumatera Selatan  5.04  5.51   6.01   5.69 -0.11
34             Sumatera Utara  5.18  5.12   5.18   5.22 -1.07>